Ex 06

### Q' inich Figueroa Coc: Gruppe 5
### Paris J. Huth: Gruppe 1

In [1]:
import xalglib
import numpy as np
import matplotlib.pyplot as plt 

In [4]:

# Define example matrix
a0 = [[1., 2., 3., 1.,],
    [2., 5., 6., 1.,],
    [3., 6., 1., 9.,],
    [1., 1., 9., 1.]]

a,d, e = xalglib.smatrixtd(a0, n = len(a0), isupper = False) # missing variable tau
a_tridiag = np.zeros((len(a0),len(a0)))
for i in range(len(a)):
    a_tridiag[i][i] = d[i]
    if i+1 < len(a):
        a_tridiag[i][i+1] = e[i]
        a_tridiag[i+1][i] = e[i] 

print('input matrix: \n', np.array(a0))
print('corresponding trdidiagonal matrix: \n', a_tridiag)

input matrix: 
 [[ 1.          2.          3.          1.        ]
 [-3.74165739 11.42857143  6.          1.        ]
 [ 0.52249722 -5.90658574 -6.81581916  9.        ]
 [ 0.17416574 -0.49167522  2.28669     2.38724773]]
corresponding trdidiagonal matrix: 
 [[ 1.         -3.74165739  0.          0.        ]
 [-3.74165739 11.42857143 -5.90658574  0.        ]
 [ 0.         -5.90658574 -6.81581916  0.        ]
 [ 0.          0.          0.          0.        ]]


In [15]:
# simple straight forward implementation of hauseholder transform
def tred2(A):
    I = np.identity(A.shape[0])
    A_c = np.copy(A)

    for k in range(A_c.shape[1]-2):
        alpha = -np.sign(A_c[k+1, k]) *  np.sqrt(np.sum(A_c[k+1,k]**2))
        r = np.sqrt(0.5*(alpha ** 2 - A_c[k+1,k] * alpha))
        v = np.zeros((A_c.shape[0],1))
        v[k+1] = (A_c[k+1,k] - alpha) / (2*r)
        v[k+2] = A_c[k+2,k].reshape(-1,1)/(2*4)
        P = I - 2*np.dot(v, v.T)
        A_c = np.dot(P, np.dot(A_c,P))
    return(A_c)

In [22]:
def tred2(A):
    A = np.array(A)  # Convert input to NumPy array
    I = np.identity(A.shape[0])
    A_c = np.copy(A)

    for k in range(A_c.shape[1]-2):
        alpha = -np.sign(A_c[k+1, k]) * np.sqrt(np.sum(A_c[k+1, k]**2))
        r = np.sqrt(0.5 * (alpha ** 2 - A_c[k+1, k] * alpha))
        v = np.zeros((A_c.shape[0], 1))
        v[k+1] = (A_c[k+1, k] - alpha) / (2 * r)
        v[k+2] = A_c[k+2, k].reshape(-1, 1) / (2 * r)
        P = I - 2 * np.dot(v, v.T)
        A_c = np.dot(P, np.dot(A_c, P))
    
    return A_c

In [25]:
# Test example from above 
# define example matrix
a0 = [[1., 2., 3., 1.,],
    [2., 5., 6., 1.,],
    [3., 6., 1., 9.,],
    [1., 1., 9., 1.]]

a_t = tred2(a0)
# input
print('input matrix A0 \n', a0)

# output of householder algorithm
print('tridiagonal form At \n', a_t)

# compare results with xalglib.smatrixtd
print('a_t - a_tridiag \n', a_t - a_tridiag)

input matrix A0 
 [[1.0, 2.0, 3.0, 1.0], [2.0, 5.0, 6.0, 1.0], [3.0, 6.0, 1.0, 9.0], [1.0, 1.0, 9.0, 1.0]]
tridiagonal form At 
 [[  1.          -6.5          4.03596866  -1.44920902]
 [ -6.5         25.25       -31.52154558   3.16737689]
 [  4.03596866 -31.52154558  17.42259004  -7.51203106]
 [ -1.44920902   3.16737689  -7.51203106   3.80345607]]
a_t - a_tridiag 
 [[  0.          -2.75834261   4.03596866  -1.44920902]
 [ -2.75834261  13.82142857 -25.61495984   3.16737689]
 [  4.03596866 -25.61495984  24.2384092   -7.51203106]
 [ -1.44920902   3.16737689  -7.51203106   3.80345607]]


In [28]:
A_large = np.ones((50,50)) + 0.000001* np.ones((50,50))
A_largel = A_large.tolist()

a, dl, el = xalglib.smatrixtd(A_largel, n = len(A_largel), isupper = False)

A_large_t = tred2(A_large)
d_t = np.diagonal(A_large_t)
e_t = np.diagonal(A_large_t, offset = 1)

print('d - dt \n', dl - d_t)
print('e - et \n', el - e_t)
print(A_large_t)


d - dt 
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
e - et 
 [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan]
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


In [27]:
import scipy.linalg as scl

# copmute the eigenvalues and vectors
ev, evec = scl.eigh_tridiagonal(d,e)

# compare eigenvalues to eigenvalues derive from np.linalg.eig 
# using the original matrix as input
ev_np, evec_np = np.linalg.eig(np.array(a0))

print('scipy Eigenvalues from tridiagonal matrix: \n', ev)
print('numpy eigenvalues from original matrix: \n',np.sort(ev_np))

scipy Eigenvalues from tridiagonal matrix: 
 [-9.09438171  0.07666752  2.83060713 14.18710706]
numpy eigenvalues from original matrix: 
 [-9.09438171  0.07666752  2.83060713 14.18710706]


In [31]:
# unpertured harmonic oscillator

# kronecker delta
def delta(n,m):
    if n==m:
        return 1.
    else:
        return 0.
    
# define hamiltonian to initialize the matrix h_nm for given size N 
def hamiltonian(N):
    h = np.zeros((N,N))
    for n in range(N):
        for m in range(N):
            h[n,m] = (n+0.5)*delta(n,m) # caluclate how q^4 looks like and calc in the same way for hw
    return h

# compute of the eigenvalues as a function of matrix size
N_i = np.arange(15,31,1)
eigenvalues = np.zeros((len(N_i),10)) 

for i in range(N_i.shape[0]):
    h_i = hamiltonian(N_i[i])
    w_i, v_i = np.linalg.eig(h_i)
    
    # eigenvalues for n = 0, 1, ..., 9
    eigenvalues[i, :] = np.sort(w_i)[:10]
    
print(eigenvalues)

[[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]]
