In [1]:
import numpy as np
import numpy.linalg as LA

# 1. Numerical linear algebra methods

### 1.1 Getting a tridiagonal matrix

In [2]:
A = np.array([[1.,2.,3.,1.],[2.,5.,6.,1.],[3.,6.,1.,9.],[1.,1.,9.,1.]])
print(A)

[[1. 2. 3. 1.]
 [2. 5. 6. 1.]
 [3. 6. 1. 9.]
 [1. 1. 9. 1.]]


In [3]:
# hauholder algorithm
def hausholder(a):
    N = len(a)
    for i in range(0,N-2):
        y = np.zeros(N)
        x = a[i]
        for j in range(0,i+1):
            y[j] = x[j]
        y[i+1] = np.sqrt(LA.norm(a[i])**2 - sum(y**2))
        w = (x-y)/LA.norm(x-y)
        P = np.identity(N) - 2*np.tensordot(w,w,0)

        a = np.matmul(a,P)
        a = np.matmul(P,a)
        
    #due to the computational error the zeros are set to 
    #extremele small values, so we manually set them to zero
    d = np.zeros(N)
    e = np.zeros(N)
    for i in range(0,N):
        d[i] = a[i,i]
        e[i] = a[i,i-1]
        for j in range(0,N):
            if abs(a[i,j]) < 1e-13:
                a[i,j] = 0
    e = e[1:]
    return d,e,a

In [4]:
hausholder(A)

(array([ 1.        , 11.42857143, -6.81581916,  2.38724773]),
 array([ 3.74165739,  5.90658574, -2.28669   ]),
 array([[ 1.        ,  3.74165739,  0.        ,  0.        ],
        [ 3.74165739, 11.42857143,  5.90658574,  0.        ],
        [ 0.        ,  5.90658574, -6.81581916, -2.28669   ],
        [ 0.        ,  0.        , -2.28669   ,  2.38724773]]))

In [5]:
B = np.array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
print(B)

[[ 4  1 -2  2]
 [ 1  2  0  1]
 [-2  0  3 -2]
 [ 2  1 -2 -1]]


In [6]:
hausholder(B)

(array([ 4.        ,  3.33333333, -1.32      ,  1.98666667]),
 array([ 3.        ,  1.66666667, -0.90666667]),
 array([[ 4.        ,  3.        ,  0.        ,  0.        ],
        [ 3.        ,  3.33333333,  1.66666667,  0.        ],
        [ 0.        ,  1.66666667, -1.32      , -0.90666667],
        [ 0.        ,  0.        , -0.90666667,  1.98666667]]))

In [7]:
C = np.zeros((50,50))
for n in range(0,50):
    for m in range(0,50):
        C[n,m] = 1/(n+m+1)
print(C)

[[1.         0.5        0.33333333 ... 0.02083333 0.02040816 0.02      ]
 [0.5        0.33333333 0.25       ... 0.02040816 0.02       0.01960784]
 [0.33333333 0.25       0.2        ... 0.02       0.01960784 0.01923077]
 ...
 [0.02083333 0.02040816 0.02       ... 0.01052632 0.01041667 0.01030928]
 [0.02040816 0.02       0.01960784 ... 0.01041667 0.01030928 0.01020408]
 [0.02       0.01960784 0.01923077 ... 0.01030928 0.01020408 0.01010101]]


In [8]:
hausholder(C)

(array([ 1.00000000e+00,  1.35580594e+00,  4.91811401e-01,  7.74994221e-02,
         1.09705895e-02,  1.47761351e-03,  1.85620756e-04,  2.16536005e-05,
         2.34706609e-06,  2.36810441e-07,  2.22842264e-08,  1.95918159e-09,
         1.61168416e-10,  1.24208091e-11,  8.97671859e-13,  6.08899839e-14,
         3.88381562e-15,  2.37357283e-16, -4.37027755e-18,  8.69118302e-18,
        -2.43263959e-18, -2.74167380e-18, -2.09331433e-18, -2.60772589e-18,
        -2.20009344e-18, -5.99811040e-18,  1.11318692e-18,  1.41834926e-18,
        -2.58739210e-18,  2.67230220e-18, -8.99248723e-19,  2.74695317e-18,
         1.83229980e-18, -8.20469744e-18,  3.83847550e-18, -5.73825175e-18,
         5.87010021e-18,  5.31036652e-18, -5.07213831e-18,  4.88867258e-19,
         3.91209153e-18,  4.46627335e-18, -5.51265877e-18,  6.58780430e-19,
        -4.90292498e-18, -1.41045999e-18,  1.79508804e-18, -9.71304142e-19,
        -3.64838663e-18,  1.24618369e-18]),
 array([ 7.90653359e-01,  4.69769564e-01,  9

alglibcode = open("C:\\Users\\notchok\Documents\\4. Semester\\ICP\\decomposition.txt")
alglibcode.readlines()


#Note: xalglib did not function with the jupiternotebook, so the code was
# written on a different compiler, the result and code was stored into 
# a .txt file which one can see here

In [12]:
import xalglib

After comparing the decomposition of the selb-programmed algorithm and the build-in function of alblib, we can notice, that the precision of alglib is higher, however the deviation from one another, in much cases, is neglectable (deviation ranges from $10^{-11}$ to $10^{-19}$). Furthermore we can notice that the off-diaganols of the decomposition made by alglib are always the negative of the off-diagonals of the self-made programm. None explanation was found for this last observation. However, after manually calculating the decomposition from B, we notice that the off-diagonals of the self-made programm have the right sign. 

In [25]:
d = np.array( [1.0, 1.355805940170721, 0.49181140051816497, 0.07749942213320171, 0.010970589495260093, 0.0014776135069851277, 0.00018562075559826603, 2.1653600480715506e-05, 2.347066094951186e-06, 2.3681044065238215e-07, 2.2284226371397748e-08, 1.959181593836033e-09, 1.6116842226714152e-10, 1.2420809305894293e-11, 8.976773451758776e-13, 6.088351545385087e-14, 3.878781080892956e-15, 2.312151743938557e-16, 7.857296372109947e-18, 4.796711991665745e-19, 7.874325166530753e-19, -1.3774846843576965e-18, 8.777884660453392e-20, -1.2936125176918119e-18, 1.5174096915204586e-18, -1.961324038775894e-18, -5.927752709878996e-19, -3.442173420171511e-18, -3.2888888718156177e-19, 8.824693141356208e-19, 7.198454265838794e-20, -3.8932163399888615e-19, -9.678843603880477e-19, 5.144657699822102e-19, -2.448146071708565e-19, -6.99874215072322e-19, -2.47736319029772e-19, -1.9742829361676505e-19, -2.6811901434510614e-19, -1.2707026065460437e-18, 1.7378027836393924e-18, 9.009942812477182e-19, -1.2675786344551837e-18, 2.6896339372630122e-18, 5.6441090758484854e-21, 1.8755368851321804e-18, 1.4702309806768671e-18, 6.763247711092436e-19, 4.775207402212735e-18, 2.4240705721217402e-18])
d2 = np.array([ 1.00000000e+00,  1.35580594e+00,  4.91811401e-01,  7.74994221e-02
  ,1.09705895e-02,  1.47761351e-03,  1.85620756e-04,  2.16536005e-05
  ,2.34706609e-06,  2.36810441e-07,  2.22842264e-08,  1.95918160e-09
  ,1.61168422e-10,  1.24208053e-11,  8.97678692e-13,  6.08921019e-14
  ,3.88049276e-15,  2.29698742e-16, -2.89575596e-19,  7.39416457e-18
 ,-3.98125497e-18,  3.48778376e-18, -6.03158111e-18,  1.51688994e-18
  ,5.94662468e-19, -3.16959372e-18, -2.09445950e-18, -7.84577672e-18
 ,-3.11013541e-18,  2.13081913e-18, -4.17233498e-19,  8.14928760e-19
  ,1.00188347e-18,  2.95059934e-18,  2.09699207e-18, -2.83565844e-18
 ,-2.37877334e-18, -2.33933619e-18,  1.33245318e-18,  1.66445154e-18
 ,-2.04966505e-18, -6.03419020e-19,  4.48432471e-18,  4.03045250e-18
  ,2.92144253e-18,-7.15113734e-18, -1.18375017e-18, -1.20592268e-18
  ,2.90688774e-18, -2.38951843e-19])
print(d-d2)

[ 0.00000000e+00  1.70720993e-10 -4.81835016e-10  3.32017053e-11
 -4.73990812e-12 -3.01487221e-12 -4.01733958e-13 -1.92844940e-14
  4.95118583e-15 -3.47617848e-16 -2.86022512e-17 -6.16396712e-18
  2.67141520e-19  4.00589429e-18 -1.34682412e-18 -8.58644615e-18
 -1.71167911e-18  1.51643239e-18  8.14687197e-18 -6.91449337e-18
  4.76868749e-18 -4.86526844e-18  6.11935996e-18 -2.81050246e-18
  9.22747224e-19  1.20826968e-18  1.50168423e-18  4.40360330e-18
  2.78124652e-18 -1.24834982e-18  4.89218041e-19 -1.20425039e-18
 -1.96976783e-18 -2.43613357e-18 -2.34180668e-18  2.13578422e-18
  2.13103702e-18  2.14190790e-18 -1.60057219e-18 -2.93515415e-18
  3.78746783e-18  1.50441330e-18 -5.75190334e-18 -1.34081856e-18
 -2.91579842e-18  9.02667423e-18  2.65398115e-18  1.88224745e-18
  1.86831966e-18  2.66302242e-18]


### 1.2 Getting eigenvalues and eigenvectors

In [14]:
import scipy.linalg as sLA

In [15]:

d1,e1,a1 = hausholder(A)
w_xalg,v_xalg = sLA.eigh_tridiagonal(d1,-e1,eigvals_only = False, select = 'a')
print('Values for eigh_tridiagonal (decomposition made by xalglib)')
print('EW:',w_xalg)
print('EV: ',v_xalg)
print()

w_sc,v_sc = sLA.eigh_tridiagonal(d1,e1,eigvals_only = False, select = 'a')
print('Values for eigh_tridiagonal (decompostion made by self-coded programm)')
print('EW:',w_sc)
print('EV: ',v_sc)
print()


w_scn,v_scn = LA.eig(a1)
print('Values for eig (self-coded programm)')
print('EW:',w_scn)
print('EV: ',v_scn)
print()

w,v = LA.eig(A)
print('Values for eig (Using A)')
print('EW:',w)

print('EV: ',v)

Values for eigh_tridiagonal (decomposition made by xalglib)
EW: [-9.09438171  0.07666752  2.83060713 14.18710706]
EV:  [[ 0.10678063  0.94870311 -0.13972794 -0.26274781]
 [ 0.28807674  0.2341124   0.06836194  0.92602906]
 [ 0.93330548 -0.15103489  0.18802531 -0.26603726]
 [-0.18587783  0.14947326  0.96976762 -0.05155525]]

Values for eigh_tridiagonal (decompostion made by self-coded programm)
EW: [-9.09438171  0.07666752  2.83060713 14.18710706]
EV:  [[ 0.10678063  0.94870311  0.13972794  0.26274781]
 [-0.28807674 -0.2341124   0.06836194  0.92602906]
 [ 0.93330548 -0.15103489 -0.18802531  0.26603726]
 [ 0.18587783 -0.14947326  0.96976762 -0.05155525]]

Values for eig (self-coded programm)
EW: [14.18710706 -9.09438171  0.07666752  2.83060713]
EV:  [[ 0.26274781 -0.10678063 -0.94870311  0.13972794]
 [ 0.92602906  0.28807674  0.2341124   0.06836194]
 [ 0.26603726 -0.93330548  0.15103489 -0.18802531]
 [-0.05155525 -0.18587783  0.14947326  0.96976762]]

Values for eig (Using A)
EW: [14.1871

In [16]:
#checking the EW and EV:

print('xalglib, scipy:')
a1 = A@v_xalg[:,0]
b1 = w_xalg[0]*v_xalg[:,0]
print(a1)
print(b1)
print()
print('self-coded, scipy:')
a1 = A@v_sc[:,0]
b1 = w_sc[0]*v_sc[:,0]
print(a1)
print(b1)
print()

print('self-coded, numpy:')
a1 = A@v_scn[:,1]
b1 = w_scn[1]*v_scn[:,1]
print(a1)
print(b1)
print()

print('A, numpy')
a1 = A@v[:,1]
b1 = w[1]*v[:,1]
print(a1)
print(b1)

xalglib, scipy:
[3.29697273 7.06790002 1.30920738 8.60872889]
[-0.97110382 -2.61987982 -8.48783631  1.6904439 ]

self-coded, scipy:
[2.51642143 4.55888829 1.19808738 8.40433106]
[-0.97110382  2.61987982 -8.48783631 -1.6904439 ]

self-coded, numpy:
[-2.51642143 -4.55888829 -1.19808738 -8.40433106]
[ 0.97110382 -2.61987982  8.48783631  1.6904439 ]

A, numpy
[-0.97110382 -2.30803871  6.68460539 -5.63504607]
[-0.97110382 -2.30803871  6.68460539 -5.63504607]


It is evident that neither the EW and EV computed with __al.xlaglib()__ nor the one computes with __hausholder()__ deliver the correct values.

# 2. perturbed QM oscillator

In [17]:
def eig_pert_oscillator(N, lamb):
    '''
    The function calculates the eigenvalues for the perturbed quantum 
    mechanical oscillator for n-Energy states, with the Hamiltonian:
    h = h0 + lamb*Q^4
    
    Input:
    N    - int: number of bounded energies to be considered
    lamb - float: magnitude of the perturbation 
    
    Output:
    w - Nx1 ndarray: The eigenvalues each repeated according to its multiplicity.
    v-  MxM ndarray: The normalized eigenvector corresponding to the eigenvalue w[i] is the array v[i].
    '''
    import numpy.linalg as LA   
    
    h0 = np.zeros((N,N))
    Q = np.zeros((N,N))
    s2 = np.zeros((N,N))
    #generating unperturbed Hamiltonian
    for n in range(0,N):
        h0[n,n] = n + 1/2
    #generating perturbation matrix. a)
    for n in range(0,N):
        for m in range(0,N):
            if n == m-1:
                Q[n,m] = np.sqrt(n+1)
            elif n ==m+1:
                Q[n,m] = np.sqrt(n)
    Q = np.sqrt(1/2)*Q
    Q4 = np.matmul(Q,Q)
    Q4 = np.matmul(Q4,Q4)

    #defining perturbated mahiltonian
    h = h0+Q4
    
    w,v = LA.eig(h)
    
    v1 = np.zeros_like(v)
    for i in range(0,len(w)):
        for j in range(0,len(w)):
            v1[i,j] = v[j,i]

    return w,v1,h

In [18]:
w,v,h= eig_pert_oscillator(50, 0.1)

In [19]:
#checking that the programm works N = 50
for i in range(0,len(h)):
    print('h@v[{}] = w[{}]*v[{}] = '.format(i,i,i),
        h@v[i], '=', w[i]*v[i]
    )


h@v[0] = w[0]*v[0] =  [-6.88413803e-13  3.65171431e-16 -7.05150623e-11  1.05546861e-15
 -2.86625000e-09  7.32856696e-16 -7.15384749e-08 -3.70702054e-15
 -1.26707851e-06 -1.39633479e-14 -1.71376351e-05 -3.27284707e-14
 -1.84971682e-04 -5.05974660e-14 -1.64003807e-03 -4.25695732e-14
 -1.21880847e-02 -1.53693427e-14 -7.70174022e-02 -4.26803943e-17
 -4.18112906e-01  9.49137290e-16 -1.96423238e+00  5.17482761e-18
 -8.02289621e+00  7.15267904e-17 -2.85603820e+01  1.38145870e-17
 -8.86257387e+01  6.90525960e-18 -2.39156063e+02  2.73524702e-18
 -5.58071245e+02  1.03454489e-18 -1.11461445e+03 -2.57949186e-19
 -1.87143600e+03 -1.40326130e-18 -2.55533334e+03 -2.19467070e-18
 -2.64291577e+03 -2.11384472e-18 -1.66190274e+03 -8.88920286e-19
  2.19454667e+02  8.93735781e-19  1.86038051e+03  1.83858510e-18
  1.83454522e+03  9.51424953e-19] = [-8.75168840e-13  1.83630939e-13 -7.04708959e-11  8.30630088e-14
 -2.86582086e-09  1.71254254e-13 -7.15384238e-08 -1.11358217e-13
 -1.26707781e-06 -1.71922339e-13

In [20]:
#estimating deviation N = 50 :
for i in range(0,len(h)):
    print('h@v[{}]- w[{}]*v[{}] = '.format(i,i,i),
        h@v[i]- w[i]*v[i]
    )


h@v[0]- w[0]*v[0] =  [ 1.86755037e-13 -1.83265768e-13 -4.41663122e-14 -8.20075402e-14
 -4.29139722e-13 -1.70521398e-13 -5.10929385e-14  1.07651197e-13
 -7.00765177e-13  1.57958991e-13  2.88474519e-13  1.85463733e-13
 -2.94439549e-13  5.46961349e-13  1.45514612e-12  2.54606024e-13
 -2.65266975e-13 -9.48300951e-14 -1.75479076e-12  9.53040190e-15
 -1.01174624e-12 -1.18565121e-15  6.05959727e-13 -8.98094666e-19
  1.51167967e-12  8.55192628e-22 -1.17239551e-13  1.51275218e-21
  1.13686838e-13  4.37954892e-21  1.30739863e-12  1.10003426e-20
  2.50111043e-12  2.37876470e-20  2.95585778e-12  4.36886497e-20
  3.63797881e-12  6.65241578e-20  7.27595761e-12  8.01083025e-20
  7.27595761e-12  6.79065771e-20  5.22959454e-12  2.31577191e-20
  1.39266376e-12 -3.45539599e-20 -4.77484718e-12 -6.24563806e-20
 -4.32009983e-12 -3.15050995e-20]
h@v[1]- w[1]*v[1] =  [ 8.07563895e-13  3.18736329e-13  1.90070189e-12 -1.77487935e-13
  1.90873099e-13  2.11621932e-13 -1.55621012e-12  1.04645120e-13
 -4.50336154e-

In [21]:
w,v,h= eig_pert_oscillator(15, 0.1)
#checking that the programm works N = 15
for i in range(0,len(h)):
    print('h@v[{}] = w[{}]*v[{}] = '.format(i,i,i),
        h@v[i], '=', w[i]*v[i]
    )

h@v[0] = w[0]*v[0] =  [1.63015946e-02 5.94475212e-14 4.62355652e-01 9.12278728e-13
 4.79941921e+00 6.86149146e-12 2.76646600e+01 3.09528868e-11
 9.92637607e+01 8.86757175e-11 2.26110230e+02 1.57921859e-10
 3.03515329e+02 1.47201286e-10 1.55541999e+02] = [1.63015946e-02 3.09666724e-14 4.62355652e-01 9.94879995e-13
 4.79941921e+00 6.87640406e-12 2.76646600e+01 3.09521199e-11
 9.92637607e+01 8.86810926e-11 2.26110230e+02 1.57931006e-10
 3.03515329e+02 1.47209812e-10 1.55541999e+02]
h@v[1] = w[1]*v[1] =  [ 1.87272712e-01  1.80216897e-15  3.53400728e+00  4.17564508e-15
  2.29099626e+01  4.50478130e-15  7.46144024e+01  6.48022714e-15
  1.24908691e+02  6.32139139e-15  7.32750547e+01 -1.70149460e-16
 -6.60804515e+01 -5.51632799e-15 -7.12765015e+01] = [ 1.87272712e-01  3.62637272e-14  3.53400728e+00  2.74252788e-14
  2.29099626e+01 -5.08165212e-15  7.46144024e+01  9.38389921e-15
  1.24908691e+02  5.44188727e-15  7.32750547e+01 -1.96622741e-16
 -6.60804515e+01 -5.11925468e-15 -7.12765015e+01]
h@

In [22]:
#estimating deviation N = 15 :
for i in range(0,len(h)):
    print('h@v[{}]- w[{}]*v[{}] = '.format(i,i,i),
        h@v[i]- w[i]*v[i]
    )

h@v[0]- w[0]*v[0] =  [-2.75231227e-14  2.84808488e-14  2.39253062e-14 -8.26012666e-14
  5.32907052e-15 -1.49125961e-14 -2.48689958e-14  7.66852802e-16
 -1.27897692e-13 -5.37508582e-15 -5.68434189e-14 -9.14737238e-15
 -3.41060513e-13 -8.52638200e-15 -5.68434189e-14]
h@v[1]- w[1]*v[1] =  [ 4.09117185e-14 -3.44615582e-14 -4.35207426e-14 -2.32496337e-14
  3.55271368e-15  9.58643341e-15 -1.42108547e-14 -2.90367207e-15
 -8.52651283e-14  8.79504111e-16 -2.84217094e-14  2.64732813e-17
 -7.10542736e-14 -3.97073311e-16  0.00000000e+00]
h@v[2]- w[2]*v[2] =  [-7.03038826e-16 -3.68871600e-14 -4.80820990e-14 -7.48290319e-14
 -1.68717634e-13 -1.42108547e-14  2.45417926e-13 -9.94759830e-14
 -1.20351530e-13 -1.13686838e-13 -1.01085808e-14 -1.13686838e-13
  4.91946769e-14 -2.84217094e-13 -4.46371911e-14]
h@v[3]- w[3]*v[3] =  [-7.34143747e-14  5.08482145e-14 -8.98683736e-14  1.77635684e-15
 -4.03066358e-14  0.00000000e+00  2.46309385e-14 -1.27897692e-13
 -4.88947819e-14 -1.42108547e-13  4.95147072e-14  8

In [23]:
w,v,h= eig_pert_oscillator(5, 0.1)
#checking that the programm works N = 15
for i in range(0,len(h)):
    print('h@v[{}] = w[{}]*v[{}] = '.format(i,i,i),
        h@v[i], '=', w[i]*v[i]
    )

h@v[0] = w[0]*v[0] =  [2.52192653e+00 4.00768251e-16 1.44115745e+01 4.67465581e-16
 1.36085339e+01] = [2.52192653e+00 1.52529616e-15 1.44115745e+01 0.00000000e+00
 1.36085339e+01]
h@v[1] = w[1]*v[1] =  [ 8.26309908e-01  2.46035410e-16 -1.77567706e-01  2.86981530e-16
  3.49146600e-02] = [ 8.26309908e-01  3.96419016e-17 -1.77567706e-01  0.00000000e+00
  3.49146600e-02]
h@v[2] = w[2]*v[2] =  [-7.20831826e-01  1.68417866e-15 -2.75454016e+00  1.96446588e-15
  3.05066996e+00] = [-7.20831826e-01  1.33867176e-15 -2.75454016e+00  0.00000000e+00
  3.05066996e+00]
h@v[3] = w[3]*v[3] =  [ 9.34022937e-15 -7.67936306e+00  5.33998916e-14 -1.82753167e+01
  5.06524749e-14] = [ 9.27017250e-15 -7.67936306e+00  5.25380487e-14 -1.82753167e+01
  5.07171908e-14]
h@v[4] = w[4]*v[4] =  [ 6.48489460e-17 -2.46776884e+00  4.13663634e-16  1.03696659e+00
 -1.13504901e-15] = [-1.01872103e-16 -2.46776884e+00  4.73355639e-16  1.03696659e+00
 -5.74170254e-16]


In [24]:
#estimating deviation N = 5 :
for i in range(0,len(h)):
    print('h@v[{}]- w[{}]*v[{}] = '.format(i,i,i),
        h@v[i]- w[i]*v[i]
    )

h@v[0]- w[0]*v[0] =  [-1.77635684e-15 -1.12452791e-15 -8.88178420e-15  4.67465581e-16
 -5.32907052e-15]
h@v[1]- w[1]*v[1] =  [ 2.22044605e-16  2.06393509e-16 -1.27675648e-15  2.86981530e-16
 -9.36750677e-16]
h@v[2]- w[2]*v[2] =  [-6.66133815e-16  3.45506901e-16 -1.77635684e-15  1.96446588e-15
  1.33226763e-15]
h@v[3]- w[3]*v[3] =  [ 7.00568690e-17 -8.88178420e-16  8.61842857e-16  0.00000000e+00
 -6.47159523e-17]
h@v[4]- w[4]*v[4] =  [ 1.66721049e-16  1.33226763e-15 -5.96920059e-17  1.99840144e-15
 -5.60878754e-16]


In [33]:
# d)
def eigenvalues_wkb(h_nm):
    # Get the size of the matrix
    size = h_nm.shape[0]

    # Initialize the eigenvalues array
    eigenvalues = np.zeros(size)

    # Iterate over each row of the matrix
    for i in range(size):
        # Initialize the coefficients for the WKB approximation
        alpha = np.zeros(size)
        beta = np.zeros(size)

        # Set the initial values for the coefficients
        alpha[size - 1] = 1.0
        beta[size - 1] = h_nm[size - 1, size - 1]

        # Perform the WKB recursion
        for j in range(size - 2, -1, -1):
            alpha[j] = h_nm[j + 1, j] * alpha[j + 1] - h_nm[j + 1, j + 1] * alpha[j + 1] - h_nm[j, j] * alpha[j + 1]
            beta[j] = h_nm[j + 1, j] * beta[j + 1] - h_nm[j, j] * beta[j + 1]

        # Calculate the eigenvalue using the WKB approximation formula
        eigenvalues[i] = beta[0] / alpha[0]

        # Shift the matrix by one row to prepare for the next iteration
        h_nm = np.roll(h_nm, -1, axis=0)

    return eigenvalues


def calculate_eigenvalues(lambda_val, n):
    size = n + 1  # Size of the matrix

    # Define the diagonal matrix h0_nm
    h0_nm = np.diag([(i + 1/2) for i in range(size)])

    # Define the matrix Q_nm
    Q_nm = np.zeros((size, size))
    for i in range(size):
        if i > 0:
            Q_nm[i][i-1] = np.sqrt(i)
        if i < size-1:
            Q_nm[i][i+1] = np.sqrt(i + 1)
    Q_nm /= np.sqrt(2)

    # Define the matrix h_nm
    h_nm = h0_nm + lambda_val * np.linalg.matrix_power(Q_nm, 4)

    # Calculate eigenvalues using the WKB approximation
    eigenvalues = eigenvalues_wkb(h_nm)

    return eigenvalues

lambda_val = 0.5
n = 5
eigenvalues = calculate_eigenvalues(lambda_val, n)
print(eigenvalues)



[0.06880245 0.         0.01589207 0.         0.04787684 0.        ]
