In [39]:
import numpy as np
import numpy.linalg as LA

# 1. Numerical linear algebra methods

### 1.1 Getting a tridiagonal matrix

In [304]:
A = np.array([[1.,2.,3.,1.],[2.,5.,6.,1.],[3.,6.,1.,9.],[1.,1.,9.,1.]])
print(A)

[[1. 2. 3. 1.]
 [2. 5. 6. 1.]
 [3. 6. 1. 9.]
 [1. 1. 9. 1.]]


In [289]:
# hauholder algorithm
def hausholder(a):
    N = len(a)
    for i in range(0,N-2):
        y = np.zeros(N)
        x = a[i]
        for j in range(0,i+1):
            y[j] = x[j]
        y[i+1] = np.sqrt(LA.norm(a[i])**2 - sum(y**2))
        w = (x-y)/LA.norm(x-y)
        P = np.identity(N) - 2*np.tensordot(w,w,0)

        a = np.matmul(a,P)
        a = np.matmul(P,a)
        
    #due to the computational error the zeros are set to 
    #extremele small values, so we manually set them to zero
    d = np.zeros(N)
    e = np.zeros(N)
    for i in range(0,N):
        d[i] = a[i,i]
        e[i] = a[i,i-1]
        for j in range(0,N):
            if abs(a[i,j]) < 1e-13:
                a[i,j] = 0
    e = e[1:]
    return d,e,a

In [290]:
hausholder(A)

(array([ 1.        , 11.42857143, -6.81581916,  2.38724773]),
 array([ 3.74165739,  5.90658574, -2.28669   ]),
 array([[ 1.        ,  3.74165739,  0.        ,  0.        ],
        [ 3.74165739, 11.42857143,  5.90658574,  0.        ],
        [ 0.        ,  5.90658574, -6.81581916, -2.28669   ],
        [ 0.        ,  0.        , -2.28669   ,  2.38724773]]))

In [291]:
B = np.array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
print(B)

[[ 4  1 -2  2]
 [ 1  2  0  1]
 [-2  0  3 -2]
 [ 2  1 -2 -1]]


In [292]:
hausholder(B)

(array([ 4.        ,  3.33333333, -1.32      ,  1.98666667]),
 array([ 3.        ,  1.66666667, -0.90666667]),
 array([[ 4.        ,  3.        ,  0.        ,  0.        ],
        [ 3.        ,  3.33333333,  1.66666667,  0.        ],
        [ 0.        ,  1.66666667, -1.32      , -0.90666667],
        [ 0.        ,  0.        , -0.90666667,  1.98666667]]))

In [293]:
C = np.zeros((50,50))
for n in range(0,50):
    for m in range(0,50):
        C[n,m] = 1/(n+m+1)
print(C)

[[1.         0.5        0.33333333 ... 0.02083333 0.02040816 0.02      ]
 [0.5        0.33333333 0.25       ... 0.02040816 0.02       0.01960784]
 [0.33333333 0.25       0.2        ... 0.02       0.01960784 0.01923077]
 ...
 [0.02083333 0.02040816 0.02       ... 0.01052632 0.01041667 0.01030928]
 [0.02040816 0.02       0.01960784 ... 0.01041667 0.01030928 0.01020408]
 [0.02       0.01960784 0.01923077 ... 0.01030928 0.01020408 0.01010101]]


In [133]:
hausholder(C)

[ 1.00000000e+00  1.35580594e+00  4.91811401e-01  7.74994221e-02
  1.09705895e-02  1.47761351e-03  1.85620756e-04  2.16536005e-05
  2.34706609e-06  2.36810441e-07  2.22842264e-08  1.95918160e-09
  1.61168422e-10  1.24208053e-11  8.97678692e-13  6.08921019e-14
  3.88049276e-15  2.29698742e-16 -2.89575596e-19  7.39416457e-18
 -3.98125497e-18  3.48778376e-18 -6.03158111e-18  1.51688994e-18
  5.94662468e-19 -3.16959372e-18 -2.09445950e-18 -7.84577672e-18
 -3.11013541e-18  2.13081913e-18 -4.17233498e-19  8.14928760e-19
  1.00188347e-18  2.95059934e-18  2.09699207e-18 -2.83565844e-18
 -2.37877334e-18 -2.33933619e-18  1.33245318e-18  1.66445154e-18
 -2.04966505e-18 -6.03419020e-19  4.48432471e-18  4.03045250e-18
  2.92144253e-18 -7.15113734e-18 -1.18375017e-18 -1.20592268e-18
  2.90688774e-18 -2.38951843e-19]
[ 7.90653359e-01  4.69769564e-01  9.46164743e-02  1.39313814e-02
  1.95864847e-03  2.57115277e-04  3.12818831e-05  3.52844404e-06
  3.69758654e-07  3.60823618e-08  3.28554052e-09  2.7964

In [284]:
alglibcode = open("C:\\Users\\notchok\Documents\\4. Semester\\ICP\\decomposition.txt")
alglibcode.readlines()


#Note: xalglib did not function with the jupiternotebook, so the code was
# written on a different compiler, the result and code was stored into 
# a .txt file which one can see here

['import xalglib as al\n',
 'import numpy as np\n',
 'def decomposition(a):\n',
 '    N = len(a)\n',
 '    tau, d, e = al.smatrixtd(a, N, False)\n',
 '\n',
 '    print("Tau:", tau)\n',
 '    print("D:", d)\n',
 '    print("E:", e)\n',
 '    \n',
 'A = [[1., 2., 3., 1.], [2., 5., 6., 1.], [3., 6., 1., 9.], [1., 1., 9., 1.]]\n',
 "print('A')\n",
 'decomposition(A)\n',
 'print()\n',
 '\n',
 "print('B')\n",
 'B = [[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]]\n',
 'decomposition(B)\n',
 'print()\n',
 "print('C')\n",
 'c = [[0 for i in range(0,50)] for j in range(0,50)]\n',
 'for n in range(0,50):\n',
 '    for m in range(0,50):\n',
 '        c[n][m] = 1/(n+m+1)\n',
 '\n',
 'decomposition(c)\n',
 '\n',
 '-----------\n',
 'A\n',
 'Tau: [1.5345224838248486, 1.6106372612444184, 0.0]\n',
 'D: [1.0, 11.42857142857143, -6.8158191618267665, 2.3872477332553377]\n',
 'E: [-3.7416573867739413, -5.906585739836577, 2.286689999901769]\n',
 '\n',
 'B\n',
 'Tau: [1.3333333333333333, 1.5999999999999999, 0.

After comparing the decomposition of the selb-programmed algorithm and the build-in function of alblib, we can notice, that the precision of alglib is higher, however the deviation from one another, in much cases, is neglectable (deviation ranges from $10^{-11}$ to $10^{-19}$). Furthermore we can notice that the Nebendiagonale of the decomposition made by alglib are always the negative of the Nebendiagonale of the self-made programm. None explanation was found for this last observation. However, after manually calculating the decomposition from B, we notice that the Nebendiagonale of the self-made programm have the right sign. 

In [145]:
d = np.array( [1.0, 1.355805940170721, 0.49181140051816497, 0.07749942213320171, 0.010970589495260093, 0.0014776135069851277, 0.00018562075559826603, 2.1653600480715506e-05, 2.347066094951186e-06, 2.3681044065238215e-07, 2.2284226371397748e-08, 1.959181593836033e-09, 1.6116842226714152e-10, 1.2420809305894293e-11, 8.976773451758776e-13, 6.088351545385087e-14, 3.878781080892956e-15, 2.312151743938557e-16, 7.857296372109947e-18, 4.796711991665745e-19, 7.874325166530753e-19, -1.3774846843576965e-18, 8.777884660453392e-20, -1.2936125176918119e-18, 1.5174096915204586e-18, -1.961324038775894e-18, -5.927752709878996e-19, -3.442173420171511e-18, -3.2888888718156177e-19, 8.824693141356208e-19, 7.198454265838794e-20, -3.8932163399888615e-19, -9.678843603880477e-19, 5.144657699822102e-19, -2.448146071708565e-19, -6.99874215072322e-19, -2.47736319029772e-19, -1.9742829361676505e-19, -2.6811901434510614e-19, -1.2707026065460437e-18, 1.7378027836393924e-18, 9.009942812477182e-19, -1.2675786344551837e-18, 2.6896339372630122e-18, 5.6441090758484854e-21, 1.8755368851321804e-18, 1.4702309806768671e-18, 6.763247711092436e-19, 4.775207402212735e-18, 2.4240705721217402e-18])
d2 = np.array([ 1.00000000e+00,  1.35580594e+00,  4.91811401e-01,  7.74994221e-02
  ,1.09705895e-02,  1.47761351e-03,  1.85620756e-04,  2.16536005e-05
  ,2.34706609e-06,  2.36810441e-07,  2.22842264e-08,  1.95918160e-09
  ,1.61168422e-10,  1.24208053e-11,  8.97678692e-13,  6.08921019e-14
  ,3.88049276e-15,  2.29698742e-16, -2.89575596e-19,  7.39416457e-18
 ,-3.98125497e-18,  3.48778376e-18, -6.03158111e-18,  1.51688994e-18
  ,5.94662468e-19, -3.16959372e-18, -2.09445950e-18, -7.84577672e-18
 ,-3.11013541e-18,  2.13081913e-18, -4.17233498e-19,  8.14928760e-19
  ,1.00188347e-18,  2.95059934e-18,  2.09699207e-18, -2.83565844e-18
 ,-2.37877334e-18, -2.33933619e-18,  1.33245318e-18,  1.66445154e-18
 ,-2.04966505e-18, -6.03419020e-19,  4.48432471e-18,  4.03045250e-18
  ,2.92144253e-18,-7.15113734e-18, -1.18375017e-18, -1.20592268e-18
  ,2.90688774e-18, -2.38951843e-19])
print(d-d2)

[ 0.00000000e+00  1.70720993e-10 -4.81835016e-10  3.32017053e-11
 -4.73990812e-12 -3.01487221e-12 -4.01733958e-13 -1.92844940e-14
  4.95118583e-15 -3.47617848e-16 -2.86022512e-17 -6.16396712e-18
  2.67141520e-19  4.00589429e-18 -1.34682412e-18 -8.58644615e-18
 -1.71167911e-18  1.51643239e-18  8.14687197e-18 -6.91449337e-18
  4.76868749e-18 -4.86526844e-18  6.11935996e-18 -2.81050246e-18
  9.22747224e-19  1.20826968e-18  1.50168423e-18  4.40360330e-18
  2.78124652e-18 -1.24834982e-18  4.89218041e-19 -1.20425039e-18
 -1.96976783e-18 -2.43613357e-18 -2.34180668e-18  2.13578422e-18
  2.13103702e-18  2.14190790e-18 -1.60057219e-18 -2.93515415e-18
  3.78746783e-18  1.50441330e-18 -5.75190334e-18 -1.34081856e-18
 -2.91579842e-18  9.02667423e-18  2.65398115e-18  1.88224745e-18
  1.86831966e-18  2.66302242e-18]


### 1.2 Getting eigenvalues and eigenvectors

In [148]:
import scipy.linalg as sLA

In [305]:

d1,e1,a1 = hausholder(A)
w_xalg,v_xalg = sLA.eigh_tridiagonal(d1,-e1,eigvals_only = False, select = 'a')
print('Values for eigh_tridiagonal (decomposition made by xalglib)')
print('EW:',w_xalg)
print('EV: ',v_xalg)
print()

w_sc,v_sc = sLA.eigh_tridiagonal(d1,e1,eigvals_only = False, select = 'a')
print('Values for eigh_tridiagonal (decompostion made by self-coded programm)')
print('EW:',w_sc)
print('EV: ',v_sc)
print()


w_scn,v_scn = LA.eig(a1)
print('Values for eig (self-coded programm)')
print('EW:',w_scn)
print('EV: ',v_scn)
print()

w,v = LA.eig(A)
print('Values for eig (Using A)')
print('EW:',w)

print('EV: ',v)

Values for eigh_tridiagonal (decomposition made by xalglib)
EW: [-9.09438171  0.07666752  2.83060713 14.18710706]
EV:  [[ 0.10678063  0.94870311 -0.13972794 -0.26274781]
 [ 0.28807674  0.2341124   0.06836194  0.92602906]
 [ 0.93330548 -0.15103489  0.18802531 -0.26603726]
 [-0.18587783  0.14947326  0.96976762 -0.05155525]]

Values for eigh_tridiagonal (decompostion made by self-coded programm)
EW: [-9.09438171  0.07666752  2.83060713 14.18710706]
EV:  [[ 0.10678063  0.94870311  0.13972794  0.26274781]
 [-0.28807674 -0.2341124   0.06836194  0.92602906]
 [ 0.93330548 -0.15103489 -0.18802531  0.26603726]
 [ 0.18587783 -0.14947326  0.96976762 -0.05155525]]

Values for eig (self-coded programm)
EW: [14.18710706 -9.09438171  0.07666752  2.83060713]
EV:  [[ 0.26274781 -0.10678063 -0.94870311  0.13972794]
 [ 0.92602906  0.28807674  0.2341124   0.06836194]
 [ 0.26603726 -0.93330548  0.15103489 -0.18802531]
 [-0.05155525 -0.18587783  0.14947326  0.96976762]]

Values for eig (Using A)
EW: [14.1871

In [318]:
#checking the EW and EV:

print('xalglib, scipy:')
a1 = A@v_xalg[:,0]
b1 = w_xalg[0]*v_xalg[:,0]
print(a1)
print(b1)
print()
print('self-coded, scipy:')
a1 = A@v_sc[:,0]
b1 = w_sc[0]*v_sc[:,0]
print(a1)
print(b1)
print()

print('self-coded, numpy:')
a1 = A@v_scn[:,1]
b1 = w_scn[1]*v_scn[:,1]
print(a1)
print(b1)
print()

print('A, numpy')
a1 = A@v[:,1]
b1 = w[1]*v[:,1]
print(a1)
print(b1)

xalglib, scipy:
[3.29697273 7.06790002 1.30920738 8.60872889]
[-0.97110382 -2.61987982 -8.48783631  1.6904439 ]

self-coded, scipy:
[2.51642143 4.55888829 1.19808738 8.40433106]
[-0.97110382  2.61987982 -8.48783631 -1.6904439 ]

self-coded, numpy:
[-2.51642143 -4.55888829 -1.19808738 -8.40433106]
[ 0.97110382 -2.61987982  8.48783631  1.6904439 ]

A, numpy
[-0.97110382 -2.30803871  6.68460539 -5.63504607]
[-0.97110382 -2.30803871  6.68460539 -5.63504607]


It is evident that neither the EW and EV computed with __al.xlaglib()__ nor the one computes with __hausholder()__ deliver the correct values.

# 2. perturbed QM oscillator

In [311]:
def eig_pert_oscillator(N, lamb):
    '''
    The function calculates the eigenvalues for the perturbed quantum 
    mechanical oscillator for n-Energy states, with the Hamiltonian:
    h = h0 + lamb*Q^4
    
    Input:
    N    - int: number of bounded energies to be considered
    lamb - float: magnitude of the perturbation 
    
    Output:
    w - Nx1 ndarray: The eigenvalues each repeated according to its multiplicity.
    v-  MxM ndarray: The normalized eigenvector corresponding to the eigenvalue w[i] is the array v[i].
    '''
    import numpy.linalg as LA   
    
    h0 = np.zeros((N,N))
    Q = np.zeros((N,N))
    s2 = np.zeros((N,N))
    #generating unperturbed Hamiltonian
    for n in range(0,N):
        h0[n,n] = n + 1/2
    #generating perturbation matrix
    for n in range(0,N):
        for m in range(0,N):
            if n == m-1:
                Q[n,m] = np.sqrt(n+1)
            elif n ==m+1:
                Q[n,m] = np.sqrt(n)
    Q = np.sqrt(1/2)*Q
    Q4 = np.matmul(Q,Q)
    Q4 = np.matmul(Q4,Q4)

    #defining perturbated mahiltonian
    h = h0+Q4
    
    w,v = LA.eig(h)
    
    v1 = np.zeros_like(v)
    for i in range(0,len(w)):
        for j in range(0,len(w)):
            v1[i,j] = v[j,i]

    return w,v1,h

In [273]:
w,v,h= eig_pert_oscillator(50, 0.1)

In [274]:
#checking that the programm works N = 50
for i in range(0,len(h)):
    print('h@v[{}] = w[{}]*v[{}] = '.format(i,i,i),
        h@v[i], '=', w[i]*v[i]
    )


h@v[0] = w[0]*v[0] =  [-6.88303923e-13  6.83136804e-17 -7.05144330e-11 -1.32588858e-15
 -2.86624588e-09 -5.72048471e-15 -7.15384724e-08 -7.61287412e-15
 -1.26707854e-06  6.42694859e-15 -1.71376351e-05  3.19893611e-14
 -1.84971682e-04  2.69261969e-14 -1.64003807e-03 -1.41529172e-14
 -1.21880847e-02 -2.48822481e-14 -7.70174022e-02 -8.57203177e-15
 -4.18112906e-01  2.89371948e-16 -1.96423238e+00  6.57342694e-17
 -8.02289621e+00  7.07399725e-17 -2.85603820e+01  1.62997395e-17
 -8.86257387e+01  7.83664884e-18 -2.39156063e+02  4.07834393e-18
 -5.58071245e+02  3.42472635e-18 -1.11461445e+03  3.93399455e-18
 -1.87143600e+03  4.88288383e-18 -2.55533334e+03  5.32734921e-18
 -2.64291577e+03  4.23835228e-18 -1.66190274e+03  1.26136246e-18
  2.19454667e+02 -2.35572643e-18  1.86038051e+03 -4.01387848e-18
  1.83454522e+03 -1.99838468e-18] = [ 1.64172739e-13  2.25244674e-13 -7.07966708e-11  6.72133811e-15
 -2.86584032e-09 -3.14192506e-13 -7.15372922e-08 -3.11357101e-13
 -1.26707867e-06 -1.41934725e-13

In [275]:
#estimating deviation N = 50 :
for i in range(0,len(h)):
    print('h@v[{}]- w[{}]*v[{}] = '.format(i,i,i),
        h@v[i]- w[i]*v[i]
    )


h@v[0]- w[0]*v[0] =  [-8.52476662e-13 -2.25176360e-13  2.82237768e-13 -8.04722670e-15
 -4.05554642e-13  3.08472021e-13 -1.18019257e-12  3.03744227e-13
  1.38523860e-13  1.48361673e-13  1.14508895e-12 -4.92384558e-13
 -4.32976110e-13 -7.00400451e-13  7.11510278e-13  6.74243241e-13
  4.71931522e-14 -5.29824876e-14 -3.65957264e-13 -2.67427489e-15
  1.26121336e-13 -1.54284121e-15  3.65929509e-13 -9.32678259e-19
 -9.98312544e-13  1.59067100e-21 -5.22248911e-13  1.65650217e-21
  8.38440428e-13  4.79575056e-21  2.58637556e-12  1.20457304e-20
  3.63797881e-12  2.60482154e-20  3.18323146e-12  4.78404956e-20
  9.54969437e-12  7.28459872e-20  1.18234311e-11  8.77208849e-20
  1.00044417e-11  7.43590990e-20  7.27595761e-12  2.53567672e-20
 -1.47792889e-12 -3.78383534e-20 -8.41282599e-12 -6.83940656e-20
 -7.04858394e-12 -3.44989449e-20]
h@v[1]- w[1]*v[1] =  [ 4.36049291e-13 -6.43698130e-13  2.11547780e-12 -1.98076979e-13
 -4.03247825e-13  1.43798816e-12 -3.18764487e-13 -3.66433078e-14
 -2.31795736e-

In [276]:
w,v,h= eig_pert_oscillator(15, 0.1)
#checking that the programm works N = 15
for i in range(0,len(h)):
    print('h@v[{}] = w[{}]*v[{}] = '.format(i,i,i),
        h@v[i], '=', w[i]*v[i]
    )

h@v[0] = w[0]*v[0] =  [1.63015946e-02 9.81192896e-16 4.62355652e-01 6.86567242e-15
 4.79941921e+00 2.37627132e-14 2.76646600e+01 8.15635174e-14
 9.92637607e+01 2.22059007e-13 2.26110230e+02 3.92614140e-13
 3.03515329e+02 3.65463629e-13 1.55541999e+02] = [ 1.63015946e-02 -2.85266721e-14  4.62355652e-01  7.22677092e-14
  4.79941921e+00  4.42849203e-14  2.76646600e+01  7.90564405e-14
  9.92637607e+01  2.21982067e-13  2.26110230e+02  3.92256431e-13
  3.03515329e+02  3.65130226e-13  1.55541999e+02]
h@v[1] = w[1]*v[1] =  [-4.16682920e-16  1.04583752e-01 -1.94389416e-14  1.62494757e+00
 -1.87961434e-13  1.22805693e+01 -1.04988611e-12  5.54463250e+01
 -3.74799074e-12  1.58865209e+02 -8.61642329e-12  2.82925829e+02
 -1.16692818e-11  2.63720076e+02 -5.99816133e-12] = [ 1.56621398e-13  1.04583752e-01 -7.98930489e-14  1.62494757e+00
 -1.65035956e-13  1.22805693e+01 -1.17116182e-12  5.54463250e+01
 -3.65370713e-12  1.58865209e+02 -8.47042010e-12  2.82925829e+02
 -1.18293223e-11  2.63720076e+02 -5.9

In [277]:
#estimating deviation N = 15 :
for i in range(0,len(h)):
    print('h@v[{}]- w[{}]*v[{}] = '.format(i,i,i),
        h@v[i]- w[i]*v[i]
    )

h@v[0]- w[0]*v[0] =  [ 7.63278329e-16  2.95078650e-14  7.40518757e-14 -6.54020368e-14
 -7.01660952e-14 -2.05222071e-14 -8.88178420e-14  2.50707691e-15
 -2.13162821e-13  7.69403185e-17  3.41060513e-13  3.57709420e-16
  0.00000000e+00  3.33403903e-16 -2.84217094e-14]
h@v[1]- w[1]*v[1] =  [-1.57038081e-13 -6.24222896e-14  6.04541073e-14 -1.10134124e-13
 -2.29254781e-14 -5.50670620e-14  1.21275704e-13 -2.34479103e-13
 -9.42836119e-14 -7.10542736e-13 -1.46003192e-13 -1.08002496e-12
  1.60040508e-13 -9.66338121e-13 -6.35378787e-14]
h@v[2]- w[2]*v[2] =  [ 7.41073869e-15  9.73423711e-15  2.39808173e-14  2.60897789e-14
  6.39488462e-14 -1.53160379e-14  1.27897692e-13  5.69756255e-15
  1.13686838e-13  3.81766691e-15  1.27897692e-13  1.75689624e-14
 -1.42108547e-14  7.77125281e-15 -2.84217094e-14]
h@v[3]- w[3]*v[3] =  [-6.63913369e-14 -1.66967696e-14  0.00000000e+00  2.28499131e-14
 -2.84217094e-14 -9.22856643e-15 -7.81597009e-14  9.86963632e-15
 -2.13162821e-14  1.19123372e-14  1.42108547e-14  1

In [279]:
w,v,h= eig_pert_oscillator(5, 0.1)
#checking that the programm works N = 15
for i in range(0,len(h)):
    print('h@v[{}] = w[{}]*v[{}] = '.format(i,i,i),
        h@v[i], '=', w[i]*v[i]
    )

h@v[0] = w[0]*v[0] =  [2.52192653e+00 8.01536502e-16 1.44115745e+01 9.34931162e-16
 1.36085339e+01] = [2.52192653e+00 3.05059231e-15 1.44115745e+01 0.00000000e+00
 1.36085339e+01]
h@v[1] = w[1]*v[1] =  [ 8.26309908e-01  4.92070820e-16 -1.77567706e-01  5.73963060e-16
  3.49146600e-02] = [ 8.26309908e-01  7.92838031e-17 -1.77567706e-01  0.00000000e+00
  3.49146600e-02]
h@v[2] = w[2]*v[2] =  [-7.20831826e-01  3.36835732e-15 -2.75454016e+00  3.92893177e-15
  3.05066996e+00] = [-7.20831826e-01  2.67734352e-15 -2.75454016e+00  0.00000000e+00
  3.05066996e+00]
h@v[3] = w[3]*v[3] =  [ 2.51515972e-14 -7.67936306e+00  1.43660920e-13 -1.82753167e+01
  1.35156293e-13] = [ 2.49945328e-14 -7.67936306e+00  1.43478887e-13 -1.82753167e+01
  1.33070693e-13]
h@v[4] = w[4]*v[4] =  [-1.82358365e-17 -2.46776884e+00  2.76550574e-16  1.03696659e+00
  1.38431395e-15] = [-1.30873787e-16 -2.46776884e+00 -2.29955255e-16  1.03696659e+00
  4.92010685e-16]


In [280]:
#estimating deviation N = 5 :
for i in range(0,len(h)):
    print('h@v[{}]- w[{}]*v[{}] = '.format(i,i,i),
        h@v[i]- w[i]*v[i]
    )

h@v[0]- w[0]*v[0] =  [-8.88178420e-15 -2.24905581e-15 -3.55271368e-15  9.34931162e-16
 -3.55271368e-15]
h@v[1]- w[1]*v[1] =  [7.77156117e-16 4.12787017e-16 2.35922393e-15 5.73963060e-16
 1.90125693e-15]
h@v[2]- w[2]*v[2] =  [ 9.99200722e-16  6.91013802e-16  2.66453526e-15  3.92893177e-15
 -3.55271368e-15]
h@v[3]- w[3]*v[3] =  [1.57064358e-16 5.32907052e-15 1.82033392e-16 2.13162821e-14
 2.08560058e-15]
h@v[4]- w[4]*v[4] =  [ 1.12637951e-16  1.33226763e-15  5.06505829e-16 -2.44249065e-15
  8.92303261e-16]
