# Numerical linear algebra methods

In [1]:
import numpy as np

In [2]:
# small program to solve the system for given epsilon with gauss jordan
def solve_equation(epsilon):
    # setup matrix
    M = np.array([[epsilon, 1/3,1/3],[1/3,1/3,1/6]])

    # perform gauss jordan
    M[0,:]=M[0,:] / M[0,0]
    M[1,:]=M[1,:] - M[0,:] * M[1,0]/M[0,0]
    M[1,:]=M[1,:] / M[1,1]
    M[0,:]=M[0,:] - M[1,:] * M[0,1]/M[1,1]

    return M[:,-1]

# solve the system
eps = 1e-12
x = solve_equation(eps)
print('x\n', x)

# Resinert oslution into matrix equation
A = np.array([[eps,1/3], [1/3,1/3]])
y = np.array([[1/3,1/6]])
y_re = np.dot(A,x)

print('A * x\n', y_re)
print(y-y_re)

x
 [-0.5  1. ]
A * x
 [0.33333333 0.16666667]
[[ 0.00000000e+00 -4.99988939e-13]]


In [6]:
from scipy.linalg import lu as ludcmp
from scipy.linalg import solve_triangular as lubksb
from scipy.linalg import inv

eps = 1e-12
A = np.array([[eps, 1/3],[1/3, 1/3]])
y = np.array([[1/3, 1/6]])

# perform lu decomposition
p, l, u = ludcmp(A)
print('p\n', p )
print('l\n', l )
print('u\n', u )
print('y\n', y)

# perform backsub
x_bs = lubksb(u, y.transpose())
print('x_bs\n', x_bs)

# Test via reinstaertion
y_re_bs = np.dot(np.dot(inv(p), A), x_bs)
print('A * x_bs \n', y_re_bs)
print('y - y_re_bs \n', y - y_re_bs)

p
 [[0. 1.]
 [1. 0.]]
l
 [[1.e+00 0.e+00]
 [3.e-12 1.e+00]]
u
 [[0.33333333 0.33333333]
 [0.         0.33333333]]
y
 [[0.33333333 0.16666667]]
x_bs
 [[0.5]
 [0.5]]
A * x_bs 
 [[0.33333333]
 [0.16666667]]
y - y_re_bs 
 [[ 0.00000000e+00 -1.66666667e-01]
 [ 1.66666667e-01 -1.00000563e-12]]
