In [96]:
import numpy as np

# 1. Numerical linear algebra methods

### _a)_

In [205]:
#programm to solve equation system using Jordan-Gauss algorith
def solve(c):
    print('equation system:')
    print(c)
    print()
    print('solution:')
    for i in range(0,len(c[0])-1):
        b = np.arange(0,len(c[0])-1)
        b = np.delete(b, i)
        c[i] = c[i]/c[i,i] 
        for j in b:
            d = c[j,i]
            c[j] = c[j]-c[i]*d
    print(c)
    print()
    for i in range(0,len(c[0])-1):
        print('x{} = {}'.format(i+1, c[i,-1]))

In [206]:
e = 1e-12
a = np.zeros((2,3))
a[0,1] = 1/3
a[1,0] = a[0,1]
a[1,1] = a[0,1]
a[0,0] = e
a[0,2] = 1/3
a[1,2] = 1/6

In [207]:
solve(a)

equation system:
[[1.00000000e-12 3.33333333e-01 3.33333333e-01]
 [3.33333333e-01 3.33333333e-01 1.66666667e-01]]

solution:
[[ 1.   0.  -0.5]
 [-0.   1.   1. ]]

x1 = -0.5
x2 = 1.0000000000015


In [208]:
a = np.array([[1.00000000e-08, 3.33333333e-01],
 [3.33333333e-01, 3.33333333e-01]])
b = np.array([-0.5,1.0000000000015])
print(np.matmul(a,b))

[0.33333333 0.16666667]


In [199]:
# checking row-wise pivoting?

### _b)_

In [198]:
from scipy.linalg import lu 
from scipy.linalg import solve_triangular as lubskb

# lu deocomposition

p,l,u = lu(a)
print('P = ', p)
print()
print('L = ',l)
print()
print('U = ',u)

#solving equation
b = np.array([1/3,1/6])

y = lubskb(l,b, lower = True)
print()
print('Ux =',y)
print()
x = lubskb(u,y)
print('x = ',x)
print()
print('A*x = ',np.matmul(p,np.matmul(a,x)))

P =  [[0. 1.]
 [1. 0.]]

L =  [[1.e+00 0.e+00]
 [3.e-12 1.e+00]]

U =  [[0.33333333 0.33333333]
 [0.         0.33333333]]

Ux = [0.33333333 0.16666667]

x =  [0.5 0.5]

A*x =  [0.33333333 0.16666667]


One can't help to notice, that both methods deliver different result for $\vec{x}$

# 2. Tridiagonal matrices 

### 2.1

In [272]:

def j_g(a):
    ''' 
    this functions applies the Jordan-Gaus algorithm to a 
    given N x N matrix
    Input:
    a - N x N np.array: Matrix A

    Output: 
    c -  N x N after transformation 
    
    Note: 
    this function does not apply pivoting
    '''
    N = len(a)
    M = len(a[0])
    c = np.zeros((N, M))
    for i in range(0, N):
        for j in range(0,M):
            c[i,j] = a[i,j]
    

    for i in range(0,N):
        b = np.arange(0,N)
        b = np.delete(b, i)
        c[i] = c[i]/c[i,i] 
        for j in b:
            d = c[j,i]
            c[j] = c[j]-c[i]*d

    return c

In [289]:
#checking that function works

a = np.array([[5,2,0,0],[7,11,3,0],[0,15,17,9],[0,0,1,8]])
b = np.ones(4)*0.5
j_g(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 2.2

### 2.3

In [277]:
#programm to solve equation system using Jordan-Gauss algorith
def solve(a,b):
    ''' 
    this functions solves the equation A*x = b by means of the 
    Jordan-Gauss algorithm
    Input:
    a - N x N np.array: Matrix A
    b - N x 1 np.array: excpected result 
    
    Output: 
    x -  N x 1 np.array: x vector 
    
    Note: this function does not apply pivoting
    '''
    #placing A and b in the same matrix C with 
    #C = (ai1, ai2,... aiN, bi)
    
    N = len(a[0])
    c = np.zeros((N, N +1))
    for i in range(0, N):
        c[i,-1] = b[i]
        for j in range(0,N):
            c[i,j] = a[i,j]
            
    print('equation system:')
    print(c)
    print()
    print('solution:')
    c_0 = j_g(c)
    print(c_0)
    print()
    x = np.zeros(N)
    for i in range(0,N):
        x[i] = c_0[i,-1]
    return x

In [290]:
#checking that functions work
solve(a,b)

equation system:
[[ 5.   2.   0.   0.   0.5]
 [ 7.  11.   3.   0.   0.5]
 [ 0.  15.  17.   9.   0.5]
 [ 0.   0.   1.   8.   0.5]]

solution:
[[ 1.          0.          0.          0.          0.11402994]
 [ 0.          1.          0.          0.         -0.03507485]
 [ 0.          0.          1.          0.          0.02920458]
 [ 0.          0.          0.          1.          0.05884943]]



array([ 0.11402994, -0.03507485,  0.02920458,  0.05884943])

### 2.4

In [285]:
#defining matrix and b vector
d = np.zeros((10,10))
a = -1
b = 3/2
c = -1
for i in range (0,10):
    d[i,i] = b
    d[i,i-1] = a
for i in range(0,9):
    d[i,i+1] = c
print(d)
y = np.ones(10)*1/10
print(y)

[[ 1.5 -1.   0.   0.   0.   0.   0.   0.   0.  -1. ]
 [-1.   1.5 -1.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.  -1.   1.5 -1.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.  -1.   1.5 -1.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.  -1.   1.5 -1.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -1.   1.5 -1.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.  -1.   1.5 -1.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.  -1.   1.5 -1.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -1.   1.5 -1. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -1.   1.5]]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [291]:
x1 = solve(d,y)
print('x = ', x1)

equation system:
[[ 1.5 -1.   0.   0.   0.   0.   0.   0.   0.  -1.   0.1]
 [-1.   1.5 -1.   0.   0.   0.   0.   0.   0.   0.   0.1]
 [ 0.  -1.   1.5 -1.   0.   0.   0.   0.   0.   0.   0.1]
 [ 0.   0.  -1.   1.5 -1.   0.   0.   0.   0.   0.   0.1]
 [ 0.   0.   0.  -1.   1.5 -1.   0.   0.   0.   0.   0.1]
 [ 0.   0.   0.   0.  -1.   1.5 -1.   0.   0.   0.   0.1]
 [ 0.   0.   0.   0.   0.  -1.   1.5 -1.   0.   0.   0.1]
 [ 0.   0.   0.   0.   0.   0.  -1.   1.5 -1.   0.   0.1]
 [ 0.   0.   0.   0.   0.   0.   0.  -1.   1.5 -1.   0.1]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -1.   1.5  0.1]]

solution:
[[ 1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.32765957]
 [ 0.          1.          0.          0.          0.          0.
   0.          0.          0.          0.          0.10638298]
 [ 0.          0.          1.          0.          0.          0.
   0.          0.          0.          0.         -0.26808511]
 [ 0

### 2.5

In [305]:
#checking the accuracy of the calculated x by computing A*x
print('calculated b = ', np.matmul(d,x1))
print()
print('differnece b- Ax =')
print(y -np.matmul(d,x1))

calculated b =  [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]

differnece b- Ax =
[-3.60822483e-16  3.05311332e-16 -1.80411242e-16  2.77555756e-17
  1.38777878e-16  8.32667268e-17 -1.94289029e-16  1.38777878e-16
  5.55111512e-17 -2.77555756e-17]


after computing the result of the operatioan $A \cdot \vec{x}$ one can notice how high accuracy of the Jordan-Gauß algorithm is the error of the calculated b is proportional to $10^{16}$